# Generated by Django 5.2.4 on 2025-07-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
    ]
