# Generated by Django 5.2.4 on 2025-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_parent_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='parent',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='age',
        ),
        migrations.AddField(
            model_name='participant',
            name='age_group',
            field=models.CharField(choices=[('U12', 'Under 12'), ('U15', 'Under 15'), ('U18', 'Under 18'), ('O18', 'Over 18')], default='muha', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default='mekonnen', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
